"""The scoreboard (brief 001, Scoreboard): filled by whatever contestants have played; the rest print "not yet".

    python -m explainers.millionaire.scoreboard     # writes SCOREBOARD.md at the repository root

Per contestant: realised winnings (mean and distribution), expected utility under the model beside the realised
mean utility, instrument spend per game, lifeline use by rung, walk-away and wrong-answer rungs. Then the
calibration table, and the wald contestant's regret against the exact game (J2). Reported as measured (rule 7).
"""
import json
import statistics
from collections import Counter
from dataclasses import dataclass, field
from fractions import Fraction
from pathlib import Path
from typing import Callable, Mapping, Sequence

from arena.report import NOT_YET, join_sections, quantile, table, usd
from explainers.millionaire import owner as O
from explainers.millionaire.oracle.game import LIFELINES, Game, regret_table
from explainers.millionaire.oracle.host import GameLog

ROOT = O.ROOT
REPO_ROOT = ROOT.parent.parent


@dataclass(frozen=True)
class Row:
    slug: str
    name: str
    expected: Callable[[Game], Fraction] | None  # expected utility from Q1 under the model; None: no model
    wald: bool = False                            # the wald contestant: "not yet" until contestant/ exists


def rows() -> list[Row]:
    from explainers.millionaire.baselines import always_answer, llm_direct
    from explainers.millionaire.oracle import play as oracle_play
    return [Row("wald", "wald", None, wald=True),
            Row("oracle", oracle_play.NAME, oracle_play.expected),
            Row("llm_direct", llm_direct.NAME, None),
            Row("always_answer", always_answer.NAME, always_answer.expected)]


@dataclass(frozen=True)
class Inputs:
    owner: Mapping
    game: Game | None                 # the fitted game, when every number exists
    missing: tuple                    # why not, otherwise
    fits: Mapping[str, dict]          # instrument -> fitted document
    logs: Mapping[str, list] = field(default_factory=dict)  # slug -> [GameLog]


def gather(root: Path = ROOT) -> Inputs:
    from explainers.millionaire.calibration.fit import reliability
    owner = O.load(root / "owner.toml")
    fits, missing = {}, []
    for k in ("llm", "phone", "audience"):
        p = root / "calibration" / "fitted" / f"{k}.json"
        if p.exists():
            fits[k] = json.loads(p.read_text())
        else:
            missing.append(f"fitted {k}")
    game = None
    try:
        rel = {k: reliability(root / "calibration" / "fitted" / f"{k}.json") for k in fits}
        if not missing:
            game = O.game(owner, rel)
    except O.MissingOwnerNumber as e:
        missing.append(e.args[0])
    for key in ("lambda_usd", "games.seed", "split_seed", "questions.path",
                *(f"instruments.{k}.{f}" for k in ("llm", "phone", "audience") for f in ("model", "usd_per_call"))):
        try:
            O.need(owner, key)
        except O.MissingOwnerNumber:
            missing.append(key)
    logs = {}
    for slug in ("oracle", "llm_direct", "always_answer"):
        p = root / "games" / f"{slug}.jsonl"
        if p.exists():
            logs[slug] = [GameLog.from_json(json.loads(line)) for line in p.read_text().splitlines() if line.strip()]
    return Inputs(owner, game, tuple(dict.fromkeys(missing)), fits, logs)


# ---------------------------------------------------------------- sections

def header(i: Inputs) -> str:
    seed = i.owner.get("games", {}).get("seed", "TBD")
    n = i.owner.get("games", {}).get("per_contestant", "TBD")
    lam = i.owner.get("lambda_usd", "TBD")
    lines = ["# Scoreboard", "",
             "Generated by `explainers/millionaire/scoreboard.py`; do not edit by hand. Brief 001, measured as it is (rule 7).", "",
             f"- Games per contestant: {n}. Games seed: {seed}. λ_usd: {lam}.",
             "- Winnings are dollars won. Utility = winnings − λ_usd × instrument spend; the model's expectations "
             "are utilities, so they sit beside the realised mean utility."]
    if i.missing:
        lines.append(f"- **Not yet played.** Missing: {', '.join(f'`{m}`' for m in i.missing)} (see QUESTIONS.md).")
    return "\n".join(lines)


def calibration(i: Inputs) -> str:
    body = []
    for k in ("llm", "phone", "audience"):
        doc = i.fits.get(k)
        if doc is None:
            body.append([k, "—", NOT_YET, "", "", "", ""])
            continue
        for t in doc["tiers"]:
            h = t["held_out"]
            rho = Fraction(t["rho"])
            body.append([k, t["tier"], f"{t['right']}/{t['right'] + t['wrong']}", f"{rho} ≈ {float(rho):.3f}",
                         h["n"], f"{h['log_score']:.4f}", f"{h['uniform_log_score']:.4f}"])
    return "## Calibration\n\n" + table(
        ["instrument", "tier", "calibration right", "ρ (Beta(1,1) mean)", "held-out n", "held-out log score",
         "uniform read"], body)


def winnings(i: Inputs) -> str:
    lam = O.lambda_usd(i.owner) if "lambda_usd" in i.owner else None
    body = []
    for row in rows():
        logs = i.logs.get(row.slug)
        if row.wald or not logs:
            body.append([row.name] + [NOT_YET] * 8)
            continue
        w = [float(g.winnings) for g in logs]
        spend = statistics.mean(float(g.spend_usd) for g in logs)
        exp = (usd(row.expected(i.game)) if i.game else "needs fits and prices") if row.expected else "— (no model)"
        util = usd(statistics.mean(float(g.utility(lam)) for g in logs)) if lam is not None else "needs λ_usd"
        body.append([row.name, len(logs), usd(statistics.mean(w)), usd(quantile(w, .1)), usd(quantile(w, .5)),
                     usd(quantile(w, .9)), exp, util, usd(spend)])
    return "## Winnings\n\n" + table(
        ["contestant", "games", "mean winnings", "P10", "median", "P90", "expected utility (model)",
         "mean utility (realised)", "spend / game"], body)


def distribution(i: Inputs) -> str:
    played = [(r, i.logs[r.slug]) for r in rows() if not r.wald and i.logs.get(r.slug)]
    if not played:
        return "## Distribution of winnings\n\n" + NOT_YET
    levels = sorted({g.winnings for _, logs in played for g in logs})
    counts = {r.slug: Counter(g.winnings for g in logs) for r, logs in played}
    return "## Distribution of winnings\n\n" + table(
        ["winnings"] + [r.name for r, _ in played],
        [[usd(v)] + [counts[r.slug][v] for r, _ in played] for v in levels])


def by_rung(i: Inputs, title: str, count: Callable[[list], Counter]) -> str:
    rungs = len(O.ladder(i.owner))
    body = []
    for row in rows():
        logs = i.logs.get(row.slug)
        if row.wald or not logs:
            body.append([row.name, NOT_YET] + [""] * (rungs - 1))
            continue
        c = count(logs)
        body.append([row.name] + [c[r] or "" for r in range(rungs)])
    return f"## {title}\n\n" + table(["contestant"] + [f"Q{r + 1}" for r in range(rungs)], body)


def lifelines(i: Inputs) -> str:
    rungs = len(O.ladder(i.owner))
    parts = []
    for row in rows():
        logs = i.logs.get(row.slug)
        if row.wald or not logs:
            parts.append(f"**{row.name}**: {NOT_YET}")
            continue
        c = Counter((k, r) for g in logs for k, r in g.lifeline_rungs.items())
        parts.append(f"**{row.name}** ({len(logs)} games)\n\n" + table(
            ["lifeline"] + [f"Q{r + 1}" for r in range(rungs)] + ["total"],
            [[k] + [c[(k, r)] or "" for r in range(rungs)] + [sum(c[(k, r)] for r in range(rungs))]
             for k in LIFELINES]))
    return "## Lifeline use by rung\n\n" + "\n\n".join(parts)


def invalid(i: Inputs) -> str:
    logs = i.logs.get("llm_direct")
    if not logs:
        return "## Invalid replies (LLM plays directly)\n\n" + NOT_YET
    bad = [q for g in logs for q in g.questions if q.invalid is not None]
    return ("## Invalid replies (LLM plays directly)\n\n"
            f"{len(bad)} of {len(logs)} games ended on an unparseable reply or a lifeline not held (counted as walks)."
            + ("\n\n" + table(["rung", "reply"], [[f"Q{q.rung + 1}", repr(q.invalid)[:80]] for q in bad[:20]])
               if bad else ""))


def regret_rows(game: Game, fmt: Callable) -> str:
    return table(["from", "exact game (oracle)", "wald estimate", "wald realised", "regret", "estimate gap"],
                 [[f"Q{r + 1}", fmt(R.exact), fmt(R.estimate), fmt(R.realised), fmt(R.regret), fmt(R.gap)]
                  for r, R in enumerate(regret_table(game))])


def regret(i: Inputs, illustrations: Sequence[tuple[str, Game, Callable]] = ()) -> str:
    out = ["## wald's regret against the exact game (J2)", "",
           "Expected utility from each rung with all three lifelines held. *wald estimate*: the per-question "
           "World's own value (lifelines priced at their option value, J1). *wald realised*: what that policy "
           "earns in the exact game. *regret* = exact − realised ≥ 0. Why they differ: lifelines are not "
           "additive (QUESTIONS.md, Findings).", ""]
    out.append(regret_rows(i.game, usd) if i.game else f"{NOT_YET}: needs {', '.join(f'`{m}`' for m in i.missing)}.")
    for title, game, fmt in illustrations:
        out += ["", f"**Illustrative, not a result: {title}.**", "", regret_rows(game, fmt)]
    return "\n".join(out)


def illustrations(owner) -> list[tuple[str, Game, Callable]]:
    from dataclasses import replace
    from explainers.millionaire.oracle.prototype import GAME, RELIABILITY
    from explainers.millionaire.oracle.game import tiers_by_fives
    brief = Game(ladder=O.ladder(owner), havens=O.havens(owner), reliability=RELIABILITY,
                 price={"llm": Fraction(1), "fifty": Fraction(0), "phone": Fraction(0), "audience": Fraction(0)},
                 tiers=tiers_by_fives(len(O.ladder(owner))), read_first=True)
    return [("the brief's ladder, read first, the prototype's illustrative ρ, $1 per read, phone and audience "
             "free", brief, usd),
            ("the prototype (proto.py's ladder in $k, the read on the menu)", GAME, lambda x: f"{float(x):,.3f}k")]


def render(i: Inputs, illustrate: bool = True) -> str:
    return join_sections([
        header(i), winnings(i), distribution(i),
        by_rung(i, "Walk-away rungs", lambda logs: Counter(g.walked_at for g in logs if g.walked_at is not None)),
        by_rung(i, "Wrong-answer rungs", lambda logs: Counter(g.wrong_at for g in logs if g.wrong_at is not None)),
        lifelines(i), invalid(i), calibration(i),
        regret(i, illustrations(i.owner) if illustrate else ()),
    ])


def main():
    out = REPO_ROOT / "SCOREBOARD.md"
    out.write_text(render(gather()))
    print(f"-> {out}")


if __name__ == "__main__":
    main()
