"""AA-Omniscience's scoreboard (brief 002, Scoreboard), rendered from a run. Reported as measured (rule 7)."""
import math
from collections import Counter
from decimal import Decimal
from fractions import Fraction

import wald

from arena import kit
from arena.report import join_sections, table
from showcases.omniscience import world as W
from showcases.omniscience.board import CONTESTANTS, paired

DRY_BANNER = ("**Dry run: self-graded, degenerate — not evidence the fit works.** `claude-haiku-4-5-20251001` is the "
              "primary, the second opinion and the grader, so the model grades its own answers and the two instruments "
              "are one. Every answer was recorded in an earlier run and is replayed here; the plates made no call. The "
              "numbers below prove the plumbing: that every observation is recorded and priced, every pack is lawful, "
              "ships its Counts and is played by wald on a plate, and every contestant is scored from the same record. "
              "They say nothing about the frozen models named in brief 002, nor about the pre-registered claims, which "
              "are untested until QUESTIONS.md's pre-registration is ruled.")


def f3(x) -> str:
    return f"{float(x):+.3f}"


def dec(x: Fraction) -> str:
    "A decimal display of an exact rational (E7 prints the rational; the run directory holds it)."
    return f"{float(x):.4f}"


def log_of(x: Fraction) -> float:
    return math.log(x.numerator) - math.log(x.denominator)


def header(o, dry_run: bool, run_dir) -> str:
    s = o.settings
    cal = sum(r["split"] == "calibration" for r in o.rows)
    lines = ["# Scoreboard — AA-Omniscience", "",
             "Generated by `showcases/omniscience/run.py`; do not edit by hand. Brief 002, revision 2 (wald "
             f"{wald.law['charter']} / {wald.law['surface']} / {wald.law['kit']}), measured as it is (rule 7).", ""]
    if dry_run:
        lines += [DRY_BANNER, ""]
    g = s.grids
    lines += [f"- Run: `{run_dir}`. Questions: {len(o.rows)} ({cal} calibration, {len(o.rows) - cal} test), "
              f"{o.per_domain[0]} per domain, drawn with seed {s.sampling_seed}, split with seed {s.split_seed}; "
              f"each plate takes the test questions in the order of seed {s.plate_seed}.",
              f"- Instruments: " + "; ".join(f"{k} `{i.model}` at ${i.usd_per_call} declared per call"
                                               for k, i in o.instruments.items()) + ".",
              f"- Grader: `{o.instruments['grader'].model}` with AA's published prompt — **not AA's grader** "
              "(`gemini-2.5-flash-preview-09-2025`, no longer served; QUESTIONS.md 2.9). It is the After-act: it "
              "grades the answer each episode submitted, or the read on an abstention.",
              f"- Buckets {', '.join(s.buckets)} (cuts {list(s.cuts)}). Globals (2.15), uniform over "
              f"{len(g.rho) ** len(s.buckets) * len(g.agree) * len(g.second) * len(g.grader)} values: ρ_b ∈ "
              f"{{{', '.join(W.num(x) for x in g.rho)}}} per bucket; (a⁺, a⁻) ∈ "
              f"{{{', '.join('(' + ', '.join(map(W.num, a)) + ')' for a in g.agree)}}}; (σ, α, β) ∈ "
              f"{{{', '.join('(' + ', '.join(map(W.num, a)) + ')' for a in g.second)}}}; γ ∈ "
              f"{{{', '.join(W.num(x) for x in g.grader)}}}.",
              f"- Penalties p: {', '.join(map(str, s.penalties))}. Second-opinion prices c (utility, a right answer "
              f"= 1): {', '.join(map(str, s.grid))}. Agreement ({s.samples} samples) costs {s.samples} × the "
              f"primary's declared price × λ_usd = {s.lambda_usd}.",
              "- *score*: mean utility of the answers (+1 right, −p wrong, 0 partial or abstained); ×100 at p = 1 "
              "is the Omniscience Index. *net*: score less what the contestant bought (grading, which every "
              "contestant gets, left out). Δ: paired per-question difference in net, ± 2 standard errors. "
              "*realised*: wald's mean utility less every price its episodes paid, the After-act's included, and c for "
              "each blind switch (E7)."]
    return "\n".join(lines)


def aa_metrics(o) -> str:
    p1, c = o.settings.penalties[0], max(o.settings.grid)
    lines = o.lines[(p1, c)]
    body = [[L.contestant, L.n, f"{100 * L.score:+.1f}", f"{100 * L.coverage:.0f}%", f"{100 * L.accuracy:.1f}%",
             f"{100 * L.hallucination:.1f}%"] for L in (lines[k] for k in CONTESTANTS)]
    return (f"## The board's own metrics (p = {p1}, c = {c})\n\n"
            + table(["contestant", "test n", "Omniscience Index", "coverage", "accuracy", "hallucination rate"], body))


def by_penalty(o) -> str:
    out = ["## Net utility per question, by penalty and second-opinion price"]
    for p in o.settings.penalties:
        body = []
        for c in o.settings.grid:
            L, po = o.lines[(p, c)], o.plates[(p, c)]
            w = L["wald"]
            (dt, st), (dr, sr) = paired(w, L["calibrated threshold"]), paired(w, L["raw model"])
            body.append([str(c)] + [f3(L[k].net) for k in CONTESTANTS]
                        + [f"{100 * w.consult_rate:.0f}% / {100 * w.agreement_rate:.0f}%", str(w.blind),
                           f"{dt:+.3f} ± {2 * st:.3f}", f"{dr:+.3f} ± {2 * sr:.3f}",
                           f3(po.realised), f3(po.realised_fresh), str(po.differ)])
        out += ["", f"**p = {p}**", "", table(
            ["c"] + list(CONTESTANTS) + ["wald consults / agreement", "blind switches (2.19)", "Δ wald − threshold",
                                         "Δ wald − raw", "wald realised, with Counts", "without Counts",
                                         "questions acted differently"], body)]
    out += ["", "A blind switch fires `answer_second` without looking at the second opinion; the World prices it at 0 "
                "and the net above charges c for it (QUESTIONS.md 2.19). *Without Counts*: the same questions, each "
                "played from the declared prior, never conditioned on the calibration or on earlier test questions."]
    return "\n".join(out)


def claims(o, dry_run: bool) -> str:
    "The four pre-registered claims, tested as QUESTIONS.md 2.13 proposes, with 2.22's c for 'no second opinion'."
    def delta(p, c, other):
        d, se = paired(o.lines[(p, c)]["wald"], o.lines[(p, c)][other])
        return d, 2 * se

    s, rows = o.settings, []
    top = max(s.grid)
    near = [c for c in s.grid if Fraction(1, 2) <= c <= 2]
    if Fraction(1) in s.penalties:
        d, e = delta(Fraction(1), top, "calibrated threshold")
        rows.append([f"(i) ties the threshold at p = 1 (c = {top}, 2.22)", f"{d:+.3f} ± {e:.3f}",
                     "held" if abs(d) <= e else "missed"])
    for p in (p for p in s.penalties if p >= 3):
        d, e = delta(p, top, "calibrated threshold")
        rows.append([f"(ii) separates from the threshold at p = {p} (c = {top})", f"{d:+.3f} ± {e:.3f}",
                     "held" if d > e else "missed"])
    for p in s.penalties:
        best = max(((c, *delta(p, c, "calibrated threshold")) for c in near), key=lambda x: x[1] - x[2], default=None)
        if best:
            c, d, e = best
            rows.append([f"(iii) separates near the stake at p = {p} (best c = {c})", f"{d:+.3f} ± {e:.3f}",
                         "held" if d > e else "missed"])
    worst = min(((p, c, *delta(p, c, "raw model")) for p in s.penalties for c in s.grid), key=lambda x: x[2] - x[3])
    rows.append([f"(iv) beats the raw model throughout (weakest: p = {worst[0]}, c = {worst[1]})",
                 f"{worst[2]:+.3f} ± {worst[3]:.3f}", "held" if worst[2] > worst[3] else "missed"])
    note = ("A dry run tests none of these: the verdicts show the test runs, on the wrong instruments.\n\n"
            if dry_run else "")
    return "## The pre-registered claims (QUESTIONS.md 2.13)\n\n" + note + table(["claim", "Δ (± 2 SE)", "verdict"], rows)


def calibration(o) -> str:
    cal = [r for r in o.rows if r["split"] == "calibration"]
    n_b = Counter(r["b"] for r in cal)
    body = [[b, n_b[b]] + [str(sum(r["g1"] == g for r in cal if r["b"] == b)) for g in ("right", "zero", "wrong")]
            for b in o.settings.buckets]
    C = o.calibration
    n = sum(C.counts.values())
    moved = []
    for comp in C.before:
        for v in C.before[comp]:
            moved.append([comp, v, dec(C.before[comp][v]), dec(C.after[comp][v])])
    first = next(iter(o.plates.values())).first
    acts = "; ".join(f"`{' → '.join(a)}` × {k}" for a, k in C.acts.most_common())
    return "\n".join([
        "## Calibration: the shipped Counts (brief 002, revision 2)", "",
        f"The calibration split played as its own plate ({n} episodes, every observation priced 0, p = "
        f"{o.settings.calibration_p}, c = {o.settings.calibration_c}; QUESTIONS.md 2.21). It wrote {len(C.counts)} "
        f"distinct records. Every test pack ships them with digest `{C.digest}` and a Score of "
        f"{len(str(C.score.numerator))}/{len(str(C.score.denominator))} digits (numerator/denominator), log "
        f"{log_of(C.score):.2f}, or {log_of(C.score) / n:.4f} per record, computed by the kit's reference and "
        "recomputed by wald at every declaration. The records, digest and exact Score are in the run directory's "
        "`calibration_counts.json`.", "",
        f"What the calibration plate bought, episode by episode: {acts}.", "",
        table(["confidence bucket", "n", "read right", "partial / declined", "wrong"], body), "",
        "**What the Counts moved.** P(Global) marginals, declared and after the shipped Counts (the kit's "
        "`post_global`, a display: nothing that decides reads it):", "",
        table(["Global", "value", "declared", "after the calibration Counts"], moved), "",
        f"On the first test question, wald played `{' → '.join(first[0])}` with the shipped Counts and "
        f"`{' → '.join(first[1])}` from the declared prior. The number of test questions it played differently, per "
        "plate, is the last column of the tables above."])


def history(h) -> str:
    return " → ".join(f"{a}={o}" for a, o in h) or "(start)"


def plates(o) -> str:
    out = ["## E7 and S15, per plate", "",
           "S15's disclosure is `Plate.disclosure()`, wald's own. E7's lines are the kit's reference "
           "(`laws/counts_check.py` at the tag `wald.law` names; QUESTIONS.md 2.23). Each line is one draw, grouped by "
           "the history in its episode that led to it: the total variation between the empirical law of its outcome "
           "and its posterior predictive under P(Global | all the plate's Counts), the shipped calibration included. "
           "Rationals are exact in the run directory's `e7.json`; the decimals here are a display. E7's policy values "
           "are expectations under the declared model over the whole plate, and the one-run maximiser's value is "
           "another; both are beyond the kit's size bound for a World of this size and are not computed "
           "(QUESTIONS.md 2.24). The realised net per question, with the Counts and from the declared prior, stands "
           "beside them."]
    seen_disclosures = {}
    for (p, c), po in sorted(o.plates.items()):
        seen_disclosures.setdefault(po.disclosure, []).append(f"p = {p}, c = {c}")
    out += ["", "**S15**, at declaration: " + " ".join(f"{'; '.join(k)}: *{d}*." for d, k in seen_disclosures.items())]
    for (p, c), po in sorted(o.plates.items()):
        rows = []
        for key, tv in sorted(po.e7.items(), key=lambda kv: (-kv[1], repr(kv[0]))):
            h, act, end = key
            rows.append([history(h), "grade" if act == kit.AFTER else act, end or "", str(po.n_by_line.get(key, "")),
                         dec(tv)])
        out += ["", f"**E7, p = {p}, c = {c}** — {po.counts_n} records in the plate's Counts at its end; the largest "
                f"line {dec(max(po.e7.values()))}. Realised net per question {f3(po.realised)} with Counts, "
                f"{f3(po.realised_fresh)} from the declared prior.", "",
                table(["history", "draw", "after end", "n", "total variation"], rows)]
    return "\n".join(out)
def spend(o) -> str:
    by = Counter()
    n = Counter()
    tokens = Counter()
    for c in o.calls:
        role = c.instrument
        by[role] += c.usd
        n[role] += 1
        tokens[(role, "in")] += c.input_tokens
        tokens[(role, "out")] += c.output_tokens
    list_prices = {"claude-haiku-4-5-20251001": (Decimal(1), Decimal(5))}
    models = {c.instrument: c.model for c in o.calls}
    body = []
    for role in sorted(by):
        lp = list_prices.get(models[role])
        at_list = (tokens[(role, "in")] * lp[0] + tokens[(role, "out")] * lp[1]) / Decimal(10**6) if lp else None
        body.append([role, n[role], tokens[(role, "in")], tokens[(role, "out")], f"${by[role]:.4f}",
                     f"${at_list:.4f}" if at_list is not None else "—"])
    total = sum(by.values(), Decimal(0))
    ungraded = sum(r["grade1"] == "UNGRADED" for r in o.rows) + sum(r["grade2"] == "UNGRADED" for r in o.rows)
    unread = sum(r["b"] == "unread" for r in o.rows)
    return ("## Spend (rule 5)\n\n" + table(["instrument", "calls", "input tokens", "output tokens",
                                             "declared $", "list-price $ from tokens"], body)
            + f"\n\nDeclared total **${total:.4f}** of a ${o.budget} budget. Grading is one call per distinct "
              f"(question, answer), shared by all four contestants. Unparseable grades: {ungraded} (scored wrong); "
              f"unparseable confidences: {unread} (bucket `unread`).")


def render(o, dry_run: bool, run_dir) -> str:
    return join_sections([header(o, dry_run, run_dir), aa_metrics(o), by_penalty(o), claims(o, dry_run),
                          calibration(o), plates(o), spend(o)])
