"""AA-Omniscience's scoreboard (brief 002, Scoreboard), rendered from a run. Reported as measured (rule 7)."""
from collections import Counter
from decimal import Decimal
from fractions import Fraction

from arena.report import join_sections, table
from showcases.omniscience.board import CONTESTANTS, paired

DRY_BANNER = ("**Dry run: self-graded, degenerate — not evidence the fit works.** `claude-haiku-4-5-20251001` is the "
              "primary, the second opinion and the grader, so the model grades its own answers and the two instruments "
              "are one. The numbers below prove the plumbing: that every observation is recorded and priced, every "
              "pack is lawful and played by wald, and every contestant is scored from the same record. They say "
              "nothing about the frozen models named in brief 002, nor about the pre-registered claims, which are untested until "
              "QUESTIONS.md's pre-registration is ruled.")


def c_name(c) -> str:
    return "none" if c is None else str(c)


def f3(x: float) -> str:
    return f"{x:+.3f}"


def header(o, dry_run: bool, run_dir) -> str:
    s = o.settings
    cal = sum(r["split"] == "calibration" for r in o.rows)
    lines = ["# Scoreboard — AA-Omniscience", "",
             "Generated by `showcases/omniscience/run.py`; do not edit by hand. Brief 002, measured as it is (rule 7).",
             ""]
    if dry_run:
        lines += [DRY_BANNER, ""]
    lines += [f"- Run: `{run_dir}`. Questions: {len(o.rows)} ({cal} calibration, {len(o.rows) - cal} test), "
              f"{o.per_domain[0]} per domain, drawn with seed {s.sampling_seed}, split with seed {s.split_seed}.",
              f"- Instruments: " + "; ".join(f"{k} `{i.model}` at ${i.usd_per_call} declared per call"
                                               for k, i in o.instruments.items()) + ".",
              f"- Grader: `{o.instruments['grader'].model}` with AA's published prompt — **not AA's grader** "
              "(`gemini-2.5-flash-preview-09-2025`, no longer served; QUESTIONS.md 2.9).",
              f"- Penalties p: {', '.join(map(str, s.penalties))}. Second-opinion prices c (utility, a right answer "
              f"= 1): {', '.join(c_name(c) for c in s.grid)}. Agreement ({s.samples} samples) costs "
              f"{s.samples} × the primary's declared price × λ_usd = {s.lambda_usd}.",
              "- *score*: mean utility of the answers (+1 right, −p wrong, 0 partial or abstained); ×100 at p = 1 "
              "is the Omniscience Index. *net*: score less what the contestant bought. Δ: paired per-question "
              "difference in net, ± 2 standard errors."]
    return "\n".join(lines)


def aa_metrics(o) -> str:
    p1 = o.settings.penalties[0]
    lines = o.lines[(p1, None)] if (p1, None) in o.lines else next(iter(o.lines.values()))
    body = [[L.contestant, L.n, f"{100 * L.score:+.1f}", f"{100 * L.coverage:.0f}%", f"{100 * L.accuracy:.1f}%",
             f"{100 * L.hallucination:.1f}%"] for L in (lines[c] for c in CONTESTANTS)]
    return (f"## The board's own metrics (p = {p1}, no second opinion)\n\n"
            + table(["contestant", "test n", "Omniscience Index", "coverage", "accuracy", "hallucination rate"], body))


def by_penalty(o) -> str:
    out = ["## Net utility per question, by penalty and second-opinion price"]
    for p in o.settings.penalties:
        body = []
        for c in o.settings.grid:
            L = o.lines[(p, c)]
            w, th, rw = L["wald"], L["calibrated threshold"], L["raw model"]
            (dt, st), (dr, sr) = paired(w, th), paired(w, rw)
            m = o.model[(p, c)]
            body.append([c_name(c)] + [f3(L[k].net) for k in CONTESTANTS]
                        + [f"{100 * w.consult_rate:.0f}% / {100 * w.agreement_rate:.0f}%",
                           f"{dt:+.3f} ± {2 * st:.3f}", f"{dr:+.3f} ± {2 * sr:.3f}",
                           f3(m["wald_expected"]), f3(m["exact"]), f"{m['exact'] - m['wald_expected']:.4f}"])
        out += ["", f"**p = {p}**", "", table(
            ["c"] + list(CONTESTANTS) + ["wald consults / agreement", "Δ wald − threshold", "Δ wald − raw",
                                         "wald expected (model)", "exact joint (oracle)", "regret"], body)]
    return "\n".join(out)


def claims(o, dry_run: bool) -> str:
    "The four pre-registered claims, tested as QUESTIONS.md 2.13 proposes. In a dry run they test nothing."
    def delta(p, c, other):
        d, se = paired(o.lines[(p, c)]["wald"], o.lines[(p, c)][other])
        return d, 2 * se

    s, rows = o.settings, []
    near = [c for c in s.grid if c is not None and Fraction(1, 2) <= c <= 2]
    if Fraction(1) in s.penalties and None in s.grid:
        d, e = delta(Fraction(1), None, "calibrated threshold")
        rows.append(["(i) ties the threshold at p = 1, no second opinion", f"{d:+.3f} ± {e:.3f}",
                     "held" if abs(d) <= e else "missed"])
    for p in (p for p in s.penalties if p >= 3):
        if None in s.grid:
            d, e = delta(p, None, "calibrated threshold")
            rows.append([f"(ii) separates from the threshold at p = {p}", f"{d:+.3f} ± {e:.3f}",
                         "held" if d > e else "missed"])
    for p in s.penalties:
        best = max(((c, *delta(p, c, "calibrated threshold")) for c in near), key=lambda x: x[1] - x[2], default=None)
        if best:
            c, d, e = best
            rows.append([f"(iii) separates near the stake at p = {p} (best c = {c})", f"{d:+.3f} ± {e:.3f}",
                         "held" if d > e else "missed"])
    worst = min(((p, c, *delta(p, c, "raw model")) for p in s.penalties for c in s.grid), key=lambda x: x[2] - x[3])
    rows.append([f"(iv) beats the raw model throughout (weakest: p = {worst[0]}, c = {c_name(worst[1])})",
                 f"{worst[2]:+.3f} ± {worst[3]:.3f}", "held" if worst[2] > worst[3] else "missed"])
    note = ("A dry run tests none of these: the verdicts show the test runs, on the wrong instruments.\n\n"
            if dry_run else "")
    return "## The pre-registered claims (QUESTIONS.md 2.13)\n\n" + note + table(["claim", "Δ (± 2 SE)", "verdict"], rows)


def calibration(o) -> str:
    f, h = o.fitted, o.held_out
    cal = [r for r in o.rows if r["split"] == "calibration"]
    n_b = Counter(r["b"] for r in cal)
    body = [[b, n_b[b]] + [f"{sum(r['g1'] == g for r in cal if r['b'] == b)}" for g in ("right", "zero", "wrong")]
            + [f"{f['g1'][b]['right']} ≈ {float(f['g1'][b]['right']):.3f}"] for b in o.settings.buckets]
    same = Counter((r["g1"], r["s"]) for r in cal)
    out = ["## Calibration (the fitted kernel)", "",
           table(["confidence bucket", "n", "read right", "partial / declined", "wrong", "P(right given bucket), fitted"],
                 body), "",
           f"Held-out log score ({h['folds']}-fold within calibration, n = {h['n']}, the scorer Millionaire uses): "
           f"joint kernel **{h['joint']:.4f}**; with the second opinion fitted by its own accuracy (independent of "
           f"the read) {h['independent_second']:.4f}; uniform {h['uniform']:.4f}. The joint kernel "
           + ("scores higher, so the dependence between the two opinions is there to be priced (J2)."
              if h["joint"] > h["independent_second"] else "does not score higher here (J2): reported as measured."),
           "", "Second opinion matched the read, by the read's grade: "
           + ", ".join(f"{g}: {same[(g, 'same')]}/{same[(g, 'same')] + same[(g, 'different')]}"
                       for g in ("right", "zero", "wrong")) + "."]
    if f["backed_off"]:
        out += ["", f"Backed off ({len(f['backed_off'])} slices below {o.settings.min_count} records): "
                + "; ".join(f"`{x}`" for x in f["backed_off"][:12]) + (" …" if len(f["backed_off"]) > 12 else "")]
    return "\n".join(out)


def spend(o) -> str:
    by = Counter()
    n = Counter()
    tokens = Counter()
    for c in o.calls:
        role = c.instrument
        by[role] += c.usd
        n[role] += 1
        tokens[(role, "in")] += c.input_tokens
        tokens[(role, "out")] += c.output_tokens
    list_prices = {"claude-haiku-4-5-20251001": (Decimal(1), Decimal(5))}
    models = {c.instrument: c.model for c in o.calls}
    body = []
    for role in sorted(by):
        lp = list_prices.get(models[role])
        at_list = (tokens[(role, "in")] * lp[0] + tokens[(role, "out")] * lp[1]) / Decimal(10**6) if lp else None
        body.append([role, n[role], tokens[(role, "in")], tokens[(role, "out")], f"${by[role]:.4f}",
                     f"${at_list:.4f}" if at_list is not None else "—"])
    total = sum(by.values(), Decimal(0))
    ungraded = sum(r["grade1"] == "UNGRADED" for r in o.rows) + sum(r["grade2"] == "UNGRADED" for r in o.rows)
    unread = sum(r["b"] == "unread" for r in o.rows)
    return ("## Spend (rule 5)\n\n" + table(["instrument", "calls", "input tokens", "output tokens",
                                             "declared $", "list-price $ from tokens"], body)
            + f"\n\nDeclared total **${total:.4f}** of a ${o.budget} budget. Grading is one call per distinct "
              f"(question, answer), shared by all four contestants. Unparseable grades: {ungraded} (scored wrong); "
              f"unparseable confidences: {unread} (bucket `unread`).")


def render(o, dry_run: bool, run_dir) -> str:
    return join_sections([header(o, dry_run, run_dir), aa_metrics(o), by_penalty(o), claims(o, dry_run), calibration(o),
                          spend(o)])
